### ISSUE TITLE
Bulletpoints

### ISSUE THREAD

**Issue by gingersnap80** [xd-admin/xd-playbook#11]
All the info we have so far is very thorough. I suggest, pending time, doing a more bullet pointed version of the descriptions we have so far. Perhaps we lead with those, then get into the detail farther down the page. Thoughts? 

ETA: I do mean as we go forward in writing guidelines and processes, thinking more in terms of bulletpoints than long paragraphs. I'm just doing a bunch of brain dumping that I think would benefit from refinement into more clear bulletpointed steps/thoughts to refer back to. Is that more clear?

**Comment by wulfsonk** [comment]
@jessicaldale should we close this?
