### ISSUE TITLE
Competitor Research - update Work Example links

### ISSUE THREAD

**Issue by wulfsonk** [xd-admin/xd-playbook#21]
Work Example links are for the Workshop, not for Competitor Research

**Comment by wulfsonk** [comment]
should link to the two AirRegi documents in the Linked Documents folder on Dropbox

**Comment by janebehrman** [comment]
Updated work example links with two AirRegi documents in Dropbox. I renamed the title for each link to match the name shown on the title slide for each PDF.

  - title: Competitive Analysis of POS systems in the USA 
    link: https://www.dropbox.com/s/b9li5jtqd1rj5ne/AirREGI_Competitive_Analysis_Example1.pdf?dl=0
  - title: AIRREGI - Research
    link: https://www.dropbox.com/s/pv0hfod2akvm4b2/AirREGI_Competitive_Analysis_Example2.pdf?dl=0
