### ISSUE TITLE
Information Architecture -- update Work Example links

### ISSUE THREAD

**Issue by wulfsonk** [xd-admin/xd-playbook#25]
TLC Content Inventory -- link should direct to Linked Documents folder on **Drive**
Lazard Intranet Content Audit -- -- link should direct to Linked Documents folder on **Drive**
Lazard Intranet Current State IA -- link should direct to Linked Documents folder on **Dropbox**
Lazard Intranet Future State IA -- link should direct to Linked Documents folder on **Dropbox**
Emirates Card Sort and IA Framework -- link should direct to Linked Documents folder on **Dropbox**

**Comment by janebehrman** [comment]
TLC Content Inventory -- link should direct to Linked Documents folder on Drive *Updated*
Lazard Intranet Content Audit -- -- link should direct to Linked Documents folder on Drive *Did not see file in IA folder*
Lazard Intranet Current State IA -- link should direct to Linked Documents folder on Dropbox *Updated*
Lazard Intranet Future State IA -- link should direct to Linked Documents folder on Dropbox *Updated*
Emirates Card Sort and IA Framework -- link should direct to Linked Documents folder on Dropbox *Updated*

**Comment by janebehrman** [comment]
The Lazard Intranet Content Audit file is currently linked to the client folder - https://docs.google.com/spreadsheets/d/1yZgBZZSUSsb8j4CCSUHpDKtamoqww_IfG4WPTWJL5es/edit#gid=1957275001. Should I copy and place in the Drive or Dropbox?

**Comment by wulfsonk** [comment]
@janebehrman yes, sorry! If you didn't already do this, it should be copied and placed in the Linked Document folder on Drive (and made read only).

**Comment by janebehrman** [comment]
@wulfsonk placed view-only copy on Drive and updated the link in the article :)
