### ISSUE TITLE
Navigation to Home

### ISSUE THREAD

**Issue by eparcell** [xd-admin/xd-playbook#3]
It took me awhile to realize that clicking on the text "Tigerspike" (upper left) was the way to navigate to the main page. 

Once figuring that out, I realized individual pages don't allow a way to navigate to the homepage, because the "tigerspike" text is replaced by the page name. That seems a little confusing. Maybe make the logo on the right navigate to home, and just have the text on the right just be text in all instances? 
![screencapture-xd-playbook-amer-tigerspike-discovery-discovery-workshop-html-1473274023545](https://cloud.githubusercontent.com/assets/4978412/18324391/215b193a-74f1-11e6-9cec-8209605dd22d.png)

**Comment by xd-admin** [comment]
this should be addressed through the new design, so going to close for now.
