### ISSUE TITLE
Design Planning Examples

### ISSUE THREAD

**Issue by eparcell** [xd-admin/xd-playbook#31]
Here's a new resource:
LAM Trello - https://trello.com/b/r1M4XvKO/design-planning

Here's an updated link for the NFLST Trello: 
https://www.dropbox.com/s/9503jlmp7r84lcs/Design-Planning-Trello.png?dl=0 
*note that it's just an IMG of the board

**Comment by janebehrman** [comment]
Updated work example and added new resource link.
