### ISSUE TITLE
Prototypes -- delete text

### ISSUE THREAD

**Issue by wulfsonk** [xd-admin/xd-playbook#53]
In the second paragraph in the "What is the technique" section, delete the phrase "at the moment" (in bold below).

note: we have created some work that fits between 3 and 4 using tools like Keynote, but at the moment the high resolution and animations that it affords comes at the expense of it’s usefulness as a prototyping tool. **At the moment** Keynote (or After Effects) are great ways to present an idea/interaction, but not great at testing actual use. We can refer to these as Interaction Examples.

**Comment by janebehrman** [comment]
Removed "At the moment' text.
