### ISSUE TITLE
Prototype Article - text edits 

### ISSUE THREAD

**Issue by eparcell** [xd-admin/xd-playbook#59]
Under Objectives / replace the first three paragraphs with the following (now more than 3 paragraphs) :)

Developing a product that requires interaction is expensive and risky — we humans can be an unpredictable bunch. Prototypes help us test ideas and solutions without the full expense of development. 

Maybe when you ask someone if they would use a product that does x, y, and z, they say “you bet I would!”. Maybe you even design a few mockups that everyone agrees looks great. But the simple act of stitching them together in a logical flow in a prototype will force some hard questions. Can the business even do this? Does the business want to do this? Is the user interested? Answering some of these questions before the design phase even starts could be helpful. 

You can “test” your solution on the client by placing your designs into Invision and walking through a basic flow. This ensures that they are looking at the design in a context much closer to real life than a pdf or jpeg. Prototypes can be a great way to test solutions internally as well. A brainstorming or sketching session might lead to many ideas, but putting a few into a low-medium fidelity prototype can be a great way of figuring out which idea is strongest.

Prototypes are also helpful for testing solutions with users. Generally (though not exclusively), prototypes tested with users should be of a relatively high resolution and fidelity, looking as close to a finished product as possible. Even if using a click-through tool like Invision, care should be taken to make sure designs are polished and click events accurately placed.

**Comment by janebehrman** [comment]
Updated text.
