### ISSUE TITLE
Design Review article 

### ISSUE THREAD

**Issue by eparcell** [xd-admin/xd-playbook#60]
Under "what" make the first mention of "heuristic review" link out to that article:

A design audit evaluates a product using the same broad categories as the <<heuristic review>>, but unlike the heuristic review the design audit does not seek to provide a quantitative measurement of every single aspect of a product’s usability profile.

**Comment by eparcell** [comment]
Oh that turned out wacky. Where the "<>" is is where the words "heuristic review" appear

**Comment by janebehrman** [comment]
Updated the text and added a link to heuristic review.
