### ISSUE TITLE
Journey Mapping - update Work Examples

### ISSUE THREAD

**Issue by wulfsonk** [xd-admin/xd-playbook#62]
1. Delete Work Examples already there (I believe you already did this?)

2. Add three work examples:
a. Alpha -- should link to Dropbox **folder**: Linked Documents --> Journey Mapping --> Examples --> Alpha

b. Discovery Communications -- should link to Dropbox **folder**: Linked Documents --> Journey Mapping --> Examples --> Discovery Communications

c. Vetshare -- should link to Dropbox **file** "Vetshare Journey Map"

**Comment by janebehrman** [comment]
Updated work examples.
