### ISSUE TITLE
Heuristic Review -- take down

### ISSUE THREAD

**Issue by wulfsonk** [xd-admin/xd-playbook#65]
Could we take down the Heuristic Review method for now? It is going to be replaced by a method called Heuristic Evaluation that is currently being written by Dubai, but may not be ready until next week.

**Comment by janebehrman** [comment]
Removed entry from dt_methods.yml

- title: Heuristic Review
  category: Method
  image: images/icon@2x.png
  link: /methods/heuristic-review.html
  text: Measure a product's usability score.
