### ISSUE TITLE
Competitor Research -- update Additional Resources

### ISSUE THREAD

**Issue by eparcell** [xd-admin/xd-playbook#69]
The additional resources for this article should be: 

Danforth Media, “Conducting a Solid UX Competitive Analysis” - link (http://danforth.co/pages/2014/03/01/conducting-a-solid-ux-competitive-analysis/)
Usability Body of Knowledge  “Competitor Analysis”- link (http://www.usabilitybok.org/competitor-analysis)
Differentiating Your Design: A Visual Approach to Competitive Reviews - link (http://www.uxmatters.com/mt/archives/2009/04/differentiating-your-design-a-visual-approach-to-competitive-reviews.php)
Amy Schade, “Competitive Usability Evaluations: Learning from Your Competition” - link (https://www.nngroup.com/articles/competitive-usability-evaluations/)

**Comment by janebehrman** [comment]
Added resources.
