### ISSUE TITLE
Story Mapping -- replace paragraph text

### ISSUE THREAD

**Issue by wulfsonk** [xd-admin/xd-playbook#73]
In the How Do I begin section, replace the paragraph with the new version below:

**Old paragraph**
Story maps can be applied many ways, so you’ll need to decide whether you’re working out an MVP 
product, or focusing on defining a specific feature. At minimum, you’ll need 3 different colors of stickies. Use one color to represent the backbone: User Activities, one color for the skeleton: user tasks, and one color details: users stories. Choose a timeframe you’re working in. A day, an entire journey, a specific event, etc.

**New paragraph:**
Story maps can be applied many ways, so you’ll need to decide whether you’re working out an MVP product, or focusing on defining a specific feature. At minimum, you’ll need 3 different colors of stickies:

- one color to represent the backbone: User Activities
- one color for the skeleton: User Tasks
- one color for details: Users Stories 

Choose a timeframe you’re working in. A day, an entire journey, a specific event, etc.

**Comment by janebehrman** [comment]
Updated copy with E. Parcell edits.
