### ISSUE TITLE
Story Maps -- formatting text 

### ISSUE THREAD

**Issue by eparcell** [xd-admin/xd-playbook#75]
Under "how do I begin", replace paragraph with this reformatted/bulleted two-paragraph version:

Story maps can be applied many ways, so you’ll need to decide whether you’re working out an MVP product, or focusing on defining a specific feature. Choose a timeframe you’re working in--a day, an entire journey, a specific event, etc.

At minimum, you’ll need 3 different colors of stickies. Use one color to represent each portion of the map:
 - Backbone: user activities
 - Skeleton: user tasks
 - Details: users stories

**Comment by janebehrman** [comment]
Updated copy.
