### ISSUE TITLE
Individual Page : Section Subheadings

### ISSUE THREAD

**Issue by eparcell** [xd-admin/xd-playbook#8]
> What decisions do I need to make? What questions should I ask? What materials will I need?

Is this guidance text going to be kept in the layout? If so, perhaps it could receive a bit different treatment when used in the long page (because it's currently very similar in appearance to body text, and therefore a bit confusing) OR perhaps it could be included in the sidebar underneath the section titles to give people a sense of what each section covers if they're trying to quickly navigate to a section.

**Comment by xd-admin** [comment]
have removed guidance "helper text".
