### ISSUE TITLE
Visual Language Brief -- text changes

### ISSUE THREAD

**Issue by eparcell** [xd-admin/xd-playbook#83]
_Under Tigerspike Process add the following text:_
The process for creating a brief is different depending on the audience—whether client or the internal team.

_Change_ "Process 1 - Direct to Client and Product Brief" 
_to_
"Process 1: Client-oriented Brief"
_and add this sentence immediately below:_ 
"The primary function of the brief is for client alignment and product direction."

_Change_ "Process 2 - Team Brief If you will be the primary designer that is working on both the brief and the product design, then the primary function of the brief is for client alignment and product direction."
_to_
"Process 2: Team-oriented Brief"
_and remove the existing sentence immediately below and replace with the following:_
"If you will not be the primary designer working on the product design, then in order to communicate with the team picking up the work, the document needs to achieve the following:"

**Comment by janebehrman** [comment]
Updated text under Tigerspike Process.
